// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARQ3qLQxzOsy0Jy2Z-jDsgUPfj96NpSQ0',
    appId: '1:984285437993:web:3566c3c87e3235a4aabc38',
    messagingSenderId: '984285437993',
    projectId: 'sheshield-ai-d81f9',
    authDomain: 'sheshield-ai-d81f9.firebaseapp.com',
    storageBucket: 'sheshield-ai-d81f9.firebasestorage.app',
    measurementId: 'G-4QBEX7QSJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk84tUEhDGhpnovTJiqd-5SSh7TApf6EY',
    appId: '1:984285437993:android:7ed41c2137058594aabc38',
    messagingSenderId: '984285437993',
    projectId: 'sheshield-ai-d81f9',
    storageBucket: 'sheshield-ai-d81f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaZy77MPsuMrQX61bgG2rlwx8ZEyWbWiU',
    appId: '1:984285437993:ios:52b8ea86dbe8707caabc38',
    messagingSenderId: '984285437993',
    projectId: 'sheshield-ai-d81f9',
    storageBucket: 'sheshield-ai-d81f9.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaZy77MPsuMrQX61bgG2rlwx8ZEyWbWiU',
    appId: '1:984285437993:ios:52b8ea86dbe8707caabc38',
    messagingSenderId: '984285437993',
    projectId: 'sheshield-ai-d81f9',
    storageBucket: 'sheshield-ai-d81f9.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARQ3qLQxzOsy0Jy2Z-jDsgUPfj96NpSQ0',
    appId: '1:984285437993:web:399659af6b8f6774aabc38',
    messagingSenderId: '984285437993',
    projectId: 'sheshield-ai-d81f9',
    authDomain: 'sheshield-ai-d81f9.firebaseapp.com',
    storageBucket: 'sheshield-ai-d81f9.firebasestorage.app',
    measurementId: 'G-27QKJK1FX3',
  );
}
